# Generated by Django 4.2.5 on 2023-10-19 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_usuario_has_genero'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='Usuario',
        ),
    ]
