# Generated by Django 4.2.5 on 2023-10-19 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_usuario_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='Usuarios',
        ),
    ]
