# Generated by Django 4.2.5 on 2023-10-19 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_usuario_idusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario_has_genero',
            fields=[
                ('idusuario_has_genero', models.AutoField(db_column='idalumno_has_genero', default=1, primary_key=True, serialize=False)),
                ('fk_genero', models.ForeignKey(db_column='fk_genero', on_delete=django.db.models.deletion.CASCADE, to='api.genero')),
                ('fk_usuario', models.ForeignKey(db_column='fk_usuario', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'usuario_has_genero',
            },
        ),
    ]
