# Generated by Django 4.2.5 on 2023-10-24 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_frecuencia_compras_num_respuestas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frecuencia_compras',
            old_name='numero_respuestas',
            new_name='num_respuestas',
        ),
    ]
