# Generated by Django 4.2.7 on 2023-12-09 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='caracteristica_aplicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.CharField(max_length=100)),
                ('num_respuestas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(db_column='descripcion', max_length=100)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(db_column='descripcion', max_length=100)),
            ],
            options={
                'db_table': 'departamentos',
            },
        ),
        migrations.CreateModel(
            name='elementos_app',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.CharField(max_length=100)),
                ('num_respuestas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('paterno', models.CharField(db_column='paterno', max_length=100)),
                ('materno', models.CharField(db_column='materno', max_length=100)),
                ('telefono', models.CharField(db_column='telefono', max_length=100)),
                ('fecha_ingreso', models.DateField(db_column='fecha_ingreso')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.departamento')),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='facilidad_navegacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.CharField(max_length=100)),
                ('num_respuestas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='frecuencia_compras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.CharField(max_length=255)),
                ('num_respuestas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipogenero', models.TextField(db_column='tipogenero')),
            ],
            options={
                'db_table': 'generos',
            },
        ),
        migrations.CreateModel(
            name='notificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.CharField(max_length=100)),
                ('num_respuestas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='problemas_tecnicos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.CharField(max_length=100)),
                ('num_respuestas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='producto_frecuente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.CharField(max_length=100)),
                ('num_respuestas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(db_column='descripcion', max_length=100)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='sistema_operativo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.CharField(max_length=100)),
                ('num_respuestas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_dispositivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.CharField(max_length=100)),
                ('num_respuestas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='uso_app',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.CharField(max_length=100)),
                ('num_respuestas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('paterno', models.CharField(db_column='paterno', max_length=100)),
                ('materno', models.CharField(db_column='materno', max_length=100)),
                ('correo', models.CharField(db_column='correo', max_length=100)),
                ('alias', models.CharField(db_column='alias', max_length=100)),
                ('password', models.CharField(db_column='password', max_length=100)),
                ('idempleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empleado')),
                ('idrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.roles')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='venta_equipo_oficina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.CharField(max_length=100)),
                ('num_respuestas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioHasGenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_genero', models.ForeignKey(db_column='fk_genero', on_delete=django.db.models.deletion.CASCADE, to='api.genero')),
                ('fk_usuario', models.ForeignKey(db_column='fk_usuario', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'usuario_has_genero',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(db_column='descripcion', max_length=100)),
                ('stock', models.IntegerField(db_column='stock')),
                ('idcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.genero'),
        ),
    ]
