# Generated by Django 4.2.7 on 2023-12-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='idcategoria',
            new_name='idcategoria_id',
        ),
        migrations.AddField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(db_column='precio', decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
