# Generated by Django 4.2.7 on 2023-12-10 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_idcategoria_productos_idcategoria_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='idcategoria_id',
            new_name='idcategoria',
        ),
    ]
