# Generated by Django 4.2.7 on 2023-12-10 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_idcategoria_id_productos_idcategoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='idcategoria',
            new_name='idcategoria_id',
        ),
    ]
