# Generated by Django 4.2.5 on 2023-10-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_usuario_has_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='caracteristica_aplicacion',
            fields=[
                ('id', models.AutoField(db_column='id', default=1, primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='respuesta', max_length=100)),
                ('num_respuestas', models.CharField(db_column='num_respuestas', max_length=100)),
            ],
            options={
                'db_table': 'caracteristica_aplicacion',
            },
        ),
        migrations.CreateModel(
            name='elementos_app',
            fields=[
                ('id', models.AutoField(db_column='id', default=1, primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='respuesta', max_length=100)),
                ('num_respuestas', models.CharField(db_column='num_respuestas', max_length=100)),
            ],
            options={
                'db_table': 'elementos_app',
            },
        ),
        migrations.CreateModel(
            name='facilidad_navegacion',
            fields=[
                ('id', models.AutoField(db_column='id', default=1, primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='respuesta', max_length=100)),
                ('num_respuestas', models.CharField(db_column='num_respuestas', max_length=100)),
            ],
            options={
                'db_table': 'facilidad_navegacion',
            },
        ),
        migrations.CreateModel(
            name='frecuencia_compras',
            fields=[
                ('id', models.AutoField(db_column='id', default=1, primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='respuesta', max_length=100)),
                ('num_respuestas', models.CharField(db_column='num_respuestas', max_length=100)),
            ],
            options={
                'db_table': 'frecuencia_compras',
            },
        ),
        migrations.CreateModel(
            name='notificacion',
            fields=[
                ('id', models.AutoField(db_column='id', default=1, primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='respuesta', max_length=100)),
                ('num_respuestas', models.CharField(db_column='num_respuestas', max_length=100)),
            ],
            options={
                'db_table': 'notificacion',
            },
        ),
        migrations.CreateModel(
            name='problemas_tecnicos',
            fields=[
                ('id', models.AutoField(db_column='id', default=1, primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='respuesta', max_length=100)),
                ('num_respuestas', models.CharField(db_column='num_respuestas', max_length=100)),
            ],
            options={
                'db_table': 'problemas_tecnicos',
            },
        ),
        migrations.CreateModel(
            name='producto_frecuente',
            fields=[
                ('id', models.AutoField(db_column='id', default=1, primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='respuesta', max_length=100)),
                ('num_respuestas', models.CharField(db_column='num_respuestas', max_length=100)),
            ],
            options={
                'db_table': 'producto_frecuente',
            },
        ),
        migrations.CreateModel(
            name='sistema_operativo',
            fields=[
                ('id', models.AutoField(db_column='id', default=1, primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='respuesta', max_length=100)),
                ('num_respuestas', models.CharField(db_column='num_respuestas', max_length=100)),
            ],
            options={
                'db_table': 'sistema_operativo',
            },
        ),
        migrations.CreateModel(
            name='tipo_dispositivo',
            fields=[
                ('id', models.AutoField(db_column='id', default=1, primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='respuesta', max_length=100)),
                ('num_respuestas', models.CharField(db_column='num_respuestas', max_length=100)),
            ],
            options={
                'db_table': 'tipo_dispositivo',
            },
        ),
        migrations.CreateModel(
            name='uso_app',
            fields=[
                ('id', models.AutoField(db_column='id', default=1, primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='respuesta', max_length=100)),
                ('num_respuestas', models.CharField(db_column='num_respuestas', max_length=100)),
            ],
            options={
                'db_table': 'uso_app',
            },
        ),
        migrations.CreateModel(
            name='venta_equipo_oficina',
            fields=[
                ('id', models.AutoField(db_column='id', default=1, primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='respuesta', max_length=100)),
                ('num_respuestas', models.CharField(db_column='num_respuestas', max_length=100)),
            ],
            options={
                'db_table': 'venta_equipo_oficina',
            },
        ),
    ]
