# Generated by Django 4.2.5 on 2023-10-19 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_caracteristica_aplicacion_elementos_app_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='caracteristica_aplicacion',
        ),
    ]
