# Generated by Django 4.2.5 on 2023-10-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_caracteristica_aplicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='caracteristica_aplicacion',
            fields=[
                ('id', models.AutoField(db_column='id', default=1, primary_key=True, serialize=False)),
                ('respuesta', models.CharField(db_column='respuesta', max_length=100)),
                ('num_respuestas', models.CharField(db_column='num_respuestas', max_length=100)),
            ],
            options={
                'db_table': 'caracteristica_aplicacion',
            },
        ),
    ]
