# Generated by Django 4.2.5 on 2023-10-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_caracteristica_aplicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frecuencia_compras',
            name='num_respuestas',
        ),
        migrations.AddField(
            model_name='frecuencia_compras',
            name='numero_respuestas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='caracteristica_aplicacion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='caracteristica_aplicacion',
            name='num_respuestas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='caracteristica_aplicacion',
            name='respuesta',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='elementos_app',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='elementos_app',
            name='num_respuestas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elementos_app',
            name='respuesta',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='facilidad_navegacion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facilidad_navegacion',
            name='num_respuestas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='facilidad_navegacion',
            name='respuesta',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='frecuencia_compras',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='frecuencia_compras',
            name='respuesta',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='num_respuestas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='respuesta',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='problemas_tecnicos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='problemas_tecnicos',
            name='num_respuestas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problemas_tecnicos',
            name='respuesta',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto_frecuente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto_frecuente',
            name='num_respuestas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto_frecuente',
            name='respuesta',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sistema_operativo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sistema_operativo',
            name='num_respuestas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sistema_operativo',
            name='respuesta',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tipo_dispositivo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipo_dispositivo',
            name='num_respuestas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tipo_dispositivo',
            name='respuesta',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='uso_app',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uso_app',
            name='num_respuestas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uso_app',
            name='respuesta',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='venta_equipo_oficina',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='venta_equipo_oficina',
            name='num_respuestas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venta_equipo_oficina',
            name='respuesta',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='caracteristica_aplicacion',
            table=None,
        ),
        migrations.AlterModelTable(
            name='elementos_app',
            table=None,
        ),
        migrations.AlterModelTable(
            name='facilidad_navegacion',
            table=None,
        ),
        migrations.AlterModelTable(
            name='frecuencia_compras',
            table=None,
        ),
        migrations.AlterModelTable(
            name='notificacion',
            table=None,
        ),
        migrations.AlterModelTable(
            name='problemas_tecnicos',
            table=None,
        ),
        migrations.AlterModelTable(
            name='producto_frecuente',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sistema_operativo',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tipo_dispositivo',
            table=None,
        ),
        migrations.AlterModelTable(
            name='uso_app',
            table=None,
        ),
        migrations.AlterModelTable(
            name='venta_equipo_oficina',
            table=None,
        ),
    ]
