# Generated by Django 4.2.7 on 2023-11-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_numero_respuestas_frecuencia_compras_num_respuestas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idEmpleado', models.AutoField(db_column='idEmpleado', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('paterno', models.CharField(db_column='paterno', max_length=100)),
                ('materno', models.CharField(db_column='materno', max_length=100)),
                ('telefono', models.CharField(db_column='telefono', max_length=100)),
                ('fecha_ingreso', models.DateField(db_column='fecha_ingreso')),
            ],
            options={
                'db_table': 'Empleados',
            },
        ),
    ]
