# Generated by Django 4.2.7 on 2023-11-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('idDepartamento', models.AutoField(db_column='idDepartamento', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=100)),
            ],
            options={
                'db_table': 'Departamentos',
            },
        ),
    ]
